### PR TITLE
CFEP-25 rebuild

### PR DESCRIPTION
**Pull request by xhochy**
Fixes #55

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@xhochy, it looks like the rerender here is producing the same problem we're seeing on https://github.com/conda-forge/aiohttp-feedstock/pull/113, namely that now there is one `use_noarch = true` build for each python version.

**Comment by xylar** [comment]
@xhochy, maybe add the equivalent of https://github.com/conda-forge/aiohttp-feedstock/pull/113/commits/a169a64668bd26b59cef34595dd543913bbd656b here (and then rerender).

**Comment by xhochy** [comment]
@conda-forge-admin please rerender

**Comment by xhochy** [comment]
Seems like that fix isn't working here.

**Comment by xylar** [comment]
That's too bad!  It looked like the same issue so I expected the same fix to work.

**Comment by xhochy** [comment]
Not pretty, but it works.

**Pull request merged**
